config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"posts#index"
  resources :users, only: [:edit, :update]
  resources :posts do
    resources :report_comments, only: :create
    resources :favorites, only: [:create, :destroy]
  end
  resources :forgets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/forget.rb
class Forget < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :date,      presence: true
  validates :image,     presence: true
  validates :object,    presence: true
  validates :place,     presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many   :report_comments
  has_many   :favorites,      dependent: :destroy

  validates :date,        presence: true
  validates :program,     presence: true
  validates :information, presence: true

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/report_comment.rb
class ReportComment < ApplicationRecord
  belongs_to  :user
  belongs_to  :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,          dependent: :destroy
  has_many :report_comments
  has_many :forgets
  has_many :favorites,      dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post_favorite = Favorite.create(user_id: current_user.id, post_id: params[:post_id])
    @post_favorite.save
  end

  def destroy
    @post_favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:post_id])
    @post_favorite.destroy
  end
end

app/controllers/forgets_controller.rb
class ForgetsController < ApplicationController
  before_action :set_forget, only: [:show, :edit, :update, :destroy]

  def index
    @forgets = Forget.all.order("date DESC")
  end

  def new
    @forget = Forget.new
  end

  def create
    @forget = Forget.new(forget_params)
    if @forget.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  private

  def forget_params
    params.require(:forget).permit(:date, :object, :place, :image).merge(user_id: current_user.id)
  end

  def set_forget
    @forget = Forget.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :user_if, only: [:edit, :destroy]

  def index
    @posts = Post.all.order("date DESC")
    @forgets = Forget.all.order("date DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @report_comments = @post.report_comments.includes(:user)
    @report_comment = ReportComment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :edit
    end
  end
  

  private

  def post_params
    params.require(:post).permit(:date, :program, :information, :feedback).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def user_if
    if @post.user_id != current_user.id
      redirect_to root_path
    end
  end 
end

app/controllers/report_comments_controller.rb
class ReportCommentsController < ApplicationController
  def create
    @report_comment = ReportComment.new(report_comment_params)
    @post = Post.find(params[:post_id])
    if @report_comment.save
      ReportCommentChannel.broadcast_to @post, {report_comment: @report_comment, user: @report_comment.user}
    end
  end

  private

  def report_comment_params
    params.require(:report_comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/forgets_helper.rb
module ForgetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/report_comments_helper.rb
module ReportCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if post.favorited?(current_user) %>
  <%= link_to post_favorite_path(post.id), method: :delete, remote: true do %>
    <span style="color:yellow">★</span> <%= post.favorites.count %>
  <% end %>
<% else %>
  <%= link_to post_favorites_path(post.id), method: :post, remote: true do %>
    <span>★ </span><%= post.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @post.id %>').html("<%= j(render "favorites/favorite", post: @post) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @post.id %>').html("<%= j(render "favorites/favorite") %>");

app/views/forgets/new.html.erb
<%= render "shared/header" %>
<div class='forget-form'>
  <h1>忘れ物投稿</h1>
  <%=form_with model: @forget, id: 'new_forget', local: true do |f|%>
    <%= f.label :date, :発見日, class: 'forget-form__label' %>
    <%= f.date_field :date, class: 'chat__room_name' %>

    <div class="forget-form__field">
      <div id="previews"></div>
      <div class="forget-form__label">
        忘れ物画像
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"forget-image" %>
      </div>
    </div>

    <div class='forget-form__field'>
      <div class='forget-form__field--left'>
        <%= f.label :object, :忘れ物, class: 'forget-form__label'%>
      </div>
      <div class='forget-form__field--right'>
        <%= f.text_field :object, class: 'chat__room_name forget-form__input' %>
      </div>
    </div>
    <div class='forget-form__field'>
      <div class='forget-form__field--left'>
        <%= f.label :place, :場所, class: 'forget-form__label'%>
      </div>
      <div class='forget-form__field--right'>
        <%= f.text_field :place, class: 'chat__room_name forget-form__input' %>
      </div>
    </div>

    <div class='forget-form__field'>
      <div class='forget-form__field--left'></div>
      <div class='forget-form__field--right'>
        <%= f.submit value: "送信", class: 'forget-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/forgets/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="detail-container">
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-post detail-date">発見日</th>
          <td class="detail-value detail-date"><%= @forget.date.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th class="detail-post detail-name">投稿者</th>
          <td class="detail-value detail-name"><%= @forget.user.name %></td>
        </tr>
        <tr>
          <%= image_tag @forget.image ,class:"item-box-img" %>
        </tr>
        <tr>
          <th class="detail-post">忘れ物</th>
          <td class="detail-value", style="white-space:pre-wrap;"><%= @forget.object %></td>
        </tr>
        <tr>
          <th class="detail-post">発見場所</th>
          <td class="detail-value", style="white-space:pre-wrap;"><%= @forget.place %></td>
        </tr>
      </tbody>
    </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bandapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render "shared/header" %>
<div class='post-form'>
  <h1>練習報告</h1>
  <%=form_with model: @post, local: true do |f|%>
    <%= f.label :date, :練習日, class: 'post-form__label' %>
    <%= f.date_field :date, class: 'chat__room_name' %>

    <div class='post-form__field'>
      <div class='post-form__field--left'>
        <%= f.label :program, :練習曲, class: 'post-form__label'%>
      </div>
      <div class='post-form__field--right'>
        <%= f.text_area :program, class: 'chat__room_name post-form__input' %>
      </div>
    </div>

    <div class='post-form__field'>
      <div class='post-form__field--left'>
        <%= f.label :information, :事務連絡, class: 'post-form__label'%>
      </div>
      <div class='post-form__field--right'>
        <%= f.text_area :information, class: 'chat__room_name post-form__input' %>
      </div>
    </div>

    <div class='post-form__field'>
      <div class='post-form__field--left'>
        <%= f.label :feedback, :感想, class: 'post-form__label'%>
      </div>
      <div class='post-form__field--right'>
        <%= f.text_area :feedback, class: 'chat__room_name post-form__input' %>
      </div>
    </div>

    <div class='post-form__field'>
      <div class='post-form__field--left'></div>
      <div class='post-form__field--right'>
        <%= f.submit value: "送信", class: 'post-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="image-opacity">

    <div class="containers">
      <div class="report-container">
        <div class="report-title">
          練習報告履歴
        </div>
        <table class="report-lists">
          <tbody>
            <% @posts.each do |post| %>
              <tr class="list">
                <%#= link_to post_path(post) do %>
                  <td class="report-date">
                    <%= link_to post.date.strftime("%Y/%m/%d"), post_path(post)  %>
                  </td>
                  <td class="report-name">
                    <%= post.user.name %>
                  </td>
                <%# end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="enquete-container">
        <div class="enquete-title">
          アンケート
        </div>
        
      </div>

      <div class="forget-container">
        <div class="forget-title">
          忘れ物一覧
        </div>
        <table class="report-lists">
          <tbody>
            <% @forgets.each do |forget| %>
              <tr class="list">
                <%#= link_to post_path(post) do %>
                  <td class="report-date">
                    <%= link_to forget.date.strftime("%Y/%m/%d"), forget_path(forget)  %>
                  </td>
                  <td class="report-name">
                    <%= forget.user.name %>
                  </td>
                <%# end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>

  </div>
</div>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<div class='post-form'>
  <h1>練習報告</h1>
  <%=form_with model: @post, local: true do |f|%>
    <%= f.label :date, :練習日, class: 'post-form__label' %>
    <%= f.date_field :date, class: 'chat__room_name' %>

    <div class='post-form__field'>
      <div class='post-form__field--left'>
        <%= f.label :program, :練習曲, class: 'post-form__label'%>
      </div>
      <div class='post-form__field--right'>
        <%= f.text_area :program, class: 'chat__room_name post-form__input' %>
      </div>
    </div>

    <div class='post-form__field'>
      <div class='post-form__field--left'>
        <%= f.label :information, :事務連絡, class: 'post-form__label'%>
      </div>
      <div class='post-form__field--right'>
        <%= f.text_area :information, class: 'chat__room_name post-form__input' %>
      </div>
    </div>

    <div class='post-form__field'>
      <div class='post-form__field--left'>
        <%= f.label :feedback, :感想, class: 'post-form__label'%>
      </div>
      <div class='post-form__field--right'>
        <%= f.text_area :feedback, class: 'chat__room_name post-form__input' %>
      </div>
    </div>

    <div class='post-form__field'>
      <div class='post-form__field--left'></div>
      <div class='post-form__field--right'>
        <%= f.submit value: "送信", class: 'post-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="detail-container">
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-post detail-date">練習日</th>
          <td class="detail-value detail-date"><%= @post.date.strftime("%Y/%m/%d()") %></td>
        </tr>
        <tr>
          <th class="detail-post detail-name">投稿者</th>
          <td class="detail-value detail-name"><%= @post.user.name %></td>
        </tr>
        <tr>
          <th class="detail-post">練習曲</th>
          <td class="detail-value", style="white-space:pre-wrap;"><%= @post.program %></td>
        </tr>
        <tr>
          <th class="detail-post">事務連絡</th>
          <td class="detail-value", style="white-space:pre-wrap;"><%= @post.information %></td>
        </tr>
        <tr>
          <th class="detail-post">感想</th>
          <td class="detail-value", style="white-space:pre-wrap;"><%= @post.feedback %></td>
        </tr>
      </tbody>
    </table>

    <div class="edit-destroy-btn-container">
      <% if current_user.id == @post.user_id %>
        <%= link_to "修正", edit_post_path(@post), method: :get, class: "post-edit-btn" %>
        <%= link_to "削除", post_path(@post), method: :delete, data: {confirm: "削除しますか?"}, class: "post-destroy-btn" %>     
      <% end %>
    </div>

    <%# いいね機能 %>
    <div id="favorite_buttons_<%= @post.id %>">
      <%= render 'favorites/favorite', post: @post %>
    </div>
    <%# いいね機能 %>

    <div id="report_comments">
      <h4>＜コメント一覧＞</h4>
      <% @post.report_comments.each do |report_comment| %>
        <div class="report-comment">
          <p class="user-info"><%= report_comment.user.name %>: </p>
          <p><%= report_comment.text %></p>
        </div>
      <% end%>
    </div>

    <div class="report_comment-form">
      <% if user_signed_in? %>
        <%= form_with model: [@post, @report_comment], id: "report_comment-form" do |f| %>
          <%= f.text_area :text, class: "report_comment-text" %>
          <%= f.submit "コメントする", class: "report_comment-submit" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>

  <div class='nav'>
    <ul class='lists-left'>
      <%= link_to 'BandApp', root_path, class: "title" %>
    </ul>

    <ul class='lists-right'>
      <li><%= link_to '練習報告', new_post_path, class: "report" %></li>
      <li><%= link_to 'アンケート', "#", class: "enquete" %></li>
      <li><%= link_to '忘れ物', new_forget_path, class: "forget" %></li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, edit_user_path(current_user), class: "user_name" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end%>
    </ul>

  </div>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>